extends RefCounted

# All ops here are involutions (applying the same op twice is identity).
# That guarantees a puzzle generated by scrambling `target` with a random
# sequence of these ops can always be solved by replaying that same
# sequence in reverse — regardless of whether the ops overlap or commute.
const CARD_TYPES := ["invert", "swap", "mirror_row", "mirror_col", "rotate180"]

static func generate(grid_size: Vector2i, target: Array, scramble_count: int, rng: RandomNumberGenerator, available_types: Array = CARD_TYPES) -> Dictionary:
	# A scramble can accidentally cancel itself out (e.g. rotate180 drawn
	# twice, or mirror_row on the same row twice), leaving the puzzle
	# already solved. Reject and retry those instead of dealing a dead hand.
	var state: Array = []
	var scramble_ops: Array = []
	var attempts := 0
	while true:
		state = []
		for row in target:
			state.append(row.duplicate(true))

		scramble_ops = []
		for i in range(scramble_count):
			var op := _random_op(grid_size, rng, available_types)
			_apply_op(state, grid_size, op)
			scramble_ops.append(op)

		attempts += 1
		if state != target or attempts >= 20:
			break

	scramble_ops.reverse()
	return {
		"initial": state,
		"hand": scramble_ops,
	}

static func _random_op(grid_size: Vector2i, rng: RandomNumberGenerator, available_types: Array) -> Dictionary:
	var type: String = available_types[rng.randi_range(0, available_types.size() - 1)]
	match type:
		"invert":
			return {
				"type": "invert",
				"params": {"x": rng.randi_range(0, grid_size.x - 1), "y": rng.randi_range(0, grid_size.y - 1)},
			}
		"swap":
			var x1 := rng.randi_range(0, grid_size.x - 1)
			var y1 := rng.randi_range(0, grid_size.y - 1)
			var x2 := rng.randi_range(0, grid_size.x - 1)
			var y2 := rng.randi_range(0, grid_size.y - 1)
			while x1 == x2 and y1 == y2:
				x2 = rng.randi_range(0, grid_size.x - 1)
				y2 = rng.randi_range(0, grid_size.y - 1)
			return {"type": "swap", "params": {"x1": x1, "y1": y1, "x2": x2, "y2": y2}}
		"mirror_row":
			return {"type": "mirror_row", "params": {"row": rng.randi_range(0, grid_size.y - 1)}}
		"mirror_col":
			return {"type": "mirror_col", "params": {"col": rng.randi_range(0, grid_size.x - 1)}}
		_:
			return {"type": "rotate180", "params": {}}

static func _apply_op(state: Array, grid_size: Vector2i, op: Dictionary) -> void:
	match op.type:
		"invert":
			state[op.params.y][op.params.x] = 1 - state[op.params.y][op.params.x]
		"swap":
			var tmp = state[op.params.y1][op.params.x1]
			state[op.params.y1][op.params.x1] = state[op.params.y2][op.params.x2]
			state[op.params.y2][op.params.x2] = tmp
		"mirror_row":
			state[op.params.row].reverse()
		"mirror_col":
			var top := 0
			var bottom := grid_size.y - 1
			while top < bottom:
				var t = state[top][op.params.col]
				state[top][op.params.col] = state[bottom][op.params.col]
				state[bottom][op.params.col] = t
				top += 1
				bottom -= 1
		"rotate180":
			var new_state := []
			for y in grid_size.y:
				var row := []
				for x in grid_size.x:
					row.append(state[grid_size.y - 1 - y][grid_size.x - 1 - x])
				new_state.append(row)
			for y in grid_size.y:
				state[y] = new_state[y]
